### ISSUE TITLE
letencrypt

### ISSUE THREAD

**Issue by eartle** [clientroomradio/clientroomradio#66]
Android doesn't like our startssl certificate. Look into using letsencrypt on the server.

**Comment by marekventur** [comment]
I like this approach: http://letsencrypt.readthedocs.org/en/latest/using.html#webroot

It creates a file and you can choose how to serve it, as long as it gets returned for a certain URL. The nginx plugin is pretty unstable at the moment.

**Comment by eartle** [comment]
Cool. I think I'm going to follow these instructions though, as I'm using apache and ubuntu 14.04 on a digital ocean box. https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04

**Comment by eartle** [comment]
Okay, that's done. Have a green padlock on Android plus the audio is working on my phone now which is exciting!

**Comment by marekventur** [comment]
yeah! Have you set up some monthly cronjob to renew or are you going to do it manually?

**Comment by eartle** [comment]
Yep, digital ocean have a script you can set up as a weekly con job. It'll try to renew it if there's less than 30 days left. The cert I got seems to last 90 days.
