### ISSUE TITLE
TESTS!

### ISSUE THREAD

**Issue by eartle** [clientroomradio/clientroomradio#69]
I'd like to have a basic travis config that ran some sanity checks, for my own sake, but also on the off chance that someone sends in a pull request.

I think this could start with just running eslint over the project, but I should fix the frontend tests and have some backend node tests.

**Comment by eartle** [comment]
@marekventur Any opinions on node testing? Something like Mocha? Travis seems to support Vows and Expresso out of the box though.

**Comment by marekventur** [comment]
Travis does support mocha, I haven't tried expresso or any of the other ones. Basically anything that returns a return code of 0 is a test, any other return code is a fail.

**Comment by eartle** [comment]
I mainly meant that Vows and Expresso are installed by default for a Travis node_js environment and that might be taken as some sort of endorsement. If I used Mocha or Gulp I'd have to install it myself, but that's no great struggle.

I'm getting this info from the Travis docs: https://docs.travis-ci.com/user/languages/javascript-with-nodejshttps://docs.travis-ci.com/user/languages/javascript-with-nodejs

**Comment by marekventur** [comment]
Travis automatically installs everything that is in package.json, so I don't think it matter much.

**Comment by eartle** [comment]
Sure. It doesn't matter that much. It's just Vows and Expresso are installed with -g before you start which, without any other opinions about node testing frameworks, I'm taking as endorsements.

**Comment by marekventur** [comment]
You don't have to install mocha or chai via "npm install mocha -g" anymore, you can just make it a dev-dependency and put the command in the script section of the package.json (npm uses the local version then): http://stackoverflow.com/posts/20384739/revisions

That way you can run all your tests via "npm test" (which is what travis will do by default)

**Comment by eartle** [comment]
I was just looking for an opinion of which one to use, but thanks anyway. I think I'll use mocha and set something basic up this evening.

**Comment by eartle** [comment]
Test framework and Travis config set up. Now there's just the small task of actually writing some tests, but I think I'll do that as I go along. If I touch something, I'll make sure there's a test for it.
